# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Nelson-Atkins Theme"
theme_version = "v0.1.0.alpha.17"
license = ""
licenselink = ""
description = ""
homepage = "https://github.com/gettypubs/quire-starter-theme/"
tags = []
features = []
min_version = ""

[author]
  name = "The Nelson-Atkins Museum of Art"
  homepage = "https://www.nelson-atkins.org"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
